  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Portfolio"
  weight = 200
  identifier = "portfolio"

  [[main]]
  name = "Technical documentation"
  weight = 210
  identifier = "technical documentation"
  url = "/awards/"
  parent = "portfolio"  

  [[main]]
  name = "Contact"
  weight = 300
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
