  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Resume"
  weight = 200
  identifier = "resume"

  [[main]]
  name = "Technical Documentation"
  weight = 300
  identifier = "technical documentation"

  [[main]]
  name = "Misc"
  weight = 400
  identifier = "misc"

  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
