  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  weight = 200
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Accomplishments"
  weight = 500
  identifier = "accomplishments"

  [[main]]
  name = "Awards"
  weight = 510
  identifier = "awards"
  name = "Technical documentation"
  weight = 210
  identifier = "technical documentation"
  url = "/awards/"
  parent = "accomplishments"  

  [[main]]
  name = "Certifications"
  weight = 520
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"
  parent = "portfolio"  

  [[main]]
  name = "Contact"
  weight = 600
  weight = 300
  identifier = "contact"
  url = "/contact/"

  [[footer]]
  name = "imprint"
  weight = 1
  identifier = "imprint"
  url = "/imprint/"
  url = "/imprint/"
